name = "CLion"

[meta]
'@keychord/chords-jetbrains/js/jetbrains.js' = { ideBinPath = '/Applications/CLion.app/Contents/MacOS/clion' }

[chords.'(.*)']
file = "@keychord/chords-jetbrains/chords/base.toml"
