name = "DataGrip"

[meta]
'@keychord/chords-jetbrains/js/jetbrains.js' = { ideBinPath = '/Applications/DataGrip.app/Contents/MacOS/datagrip' }

[chords.'(.*)']
file = "@keychord/chords-jetbrains/chords/base.toml"
