name = "RubyMine"

[meta]
'@keychord/chords-jetbrains/js/jetbrains.js' = { ideBinPath = '/Applications/RubyMine.app/Contents/MacOS/rubymine' }

[chords.'(.*)']
file = "@keychord/chords-jetbrains/chords/base.toml"
