[config]
name = "WebStorm"
extends = "@keychord/chords-jetbrains/chords/base.toml"

[config.js]
module = '''
import buildHandler from 'dist/jetbrains.js';
export default buildHandler(
  import.meta,
  "/Applications/WebStorm.app/Contents/MacOS/webstorm"
)
'''
