name = "WebStorm"

[meta]
'@keychord/chords-jetbrains/js/jetbrains.js' = { ideBinPath = '/Applications/WebStorm.app/Contents/MacOS/webstorm' }

[chords.'(.*)']
file = "@keychord/chords-jetbrains/chords/base.toml"
