name = "IntelliJ IDEA"

[meta]
'@keychords/chords-jetbrains' = { ideBinPath = '/Applications/IntelliJ IDEA.app/Contents/MacOS/idea' }

[chords.'(.*)']
file = "@keychords/chords-jetbrains/chords/base.toml"
