name = "RustRover"

[meta]
'@keychord/chords-jetbrains/js/jetbrains.js' = { ideBinPath = '/Applications/RustRover.app/Contents/MacOS/rustrover' }

[chords.'(.*)']
file = "@keychord/chords-jetbrains/chords/base.toml"
