name = "RustRover"

[meta]
'@keychords/chords-jetbrains' = { ideBinPath = '/Applications/RustRover.app/Contents/MacOS/rustrover' }

[chords.'(.*)']
file = "@keychords/chords-jetbrains/chords/base.toml"
